name: LottoGenerate Runner
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello-World-step
        run: echo "Hello World!"

      - name: Display changed files
        id: changedPath
        run: |
          echo "Changed files:"
          CHANGED_FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$CHANGED_FILE"
