name: LottoGenerate Runner
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "producer/*"

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello-World-step
        run: echo "Hello World!"

      - name: Display changed files
        id: changedPath
        run: |
          echo "Changed files:"
          echo "test3 added and working with producer folder"
          echo "test and test2 removed working with producer folder test2"
