name: LottoGenerate Runner
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: my-step
        run: echo "Hello World!"
      
      - name: Display changed files
        run: |
          echo "Changed files:"
